entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https

  web-secure:
    address: :443

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  le:
    acme:
      email: ian.ernst.chai@gmail.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web